name: 'Multi-Language Sanity Check'
description: 'Automated sanity checks and vulnerability scanning for multi-language projects'
author: 'Surabhis12'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for posting comments and managing labels'
    required: true
    default: ${{ github.token }}

outputs:
  status:
    description: 'Overall status of sanity checks (success/failure)'
    value: ${{ steps.run-checks.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: |
          **/*.c
          **/*.cpp
          **/*.h
          **/*.hpp
          **/*.js
          **/*.jsx
          **/*.ts
          **/*.tsx
          **/*.rs
          **/*.kt
          **/*.swift
          **/*.java
          **/*.dart
    
    - name: Detect languages and setup
      if: steps.changed-files.outputs.any_changed == 'true'
      id: detect
      shell: bash
      run: |
        echo "=== Language Detection ==="
        
        # Get the action's path
        ACTION_PATH="${{ github.action_path }}"
        
        # Write changed files
        echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt
        
        # Initialize detection flags
        HAS_CPP=false
        HAS_JS=false
        HAS_RUST=false
        HAS_KOTLIN=false
        HAS_SWIFT=false
        HAS_JAVA=false
        HAS_FLUTTER=false
        
        # Clean old files
        rm -f cpp_files.txt js_files.txt rust_files.txt kotlin_files.txt swift_files.txt java_files.txt flutter_files.txt
        
        # Process each changed file
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          case "$file" in
            *.c|*.cpp|*.h|*.hpp)
              HAS_CPP=true
              echo "$file" >> cpp_files.txt
              ;;
            *.js|*.jsx|*.ts|*.tsx)
              HAS_JS=true
              echo "$file" >> js_files.txt
              ;;
            *.rs)
              HAS_RUST=true
              echo "$file" >> rust_files.txt
              ;;
            *.kt)
              HAS_KOTLIN=true
              echo "$file" >> kotlin_files.txt
              ;;
            *.swift)
              HAS_SWIFT=true
              echo "$file" >> swift_files.txt
              ;;
            *.java)
              HAS_JAVA=true
              echo "$file" >> java_files.txt
              ;;
            *.dart)
              HAS_FLUTTER=true
              echo "$file" >> flutter_files.txt
              ;;
          esac
        done
        
        # Show detected files
        [ "$HAS_CPP" = true ] && echo "✓ C/C++ detected: $(wc -l < cpp_files.txt 2>/dev/null || echo 0) files"
        [ "$HAS_JS" = true ] && echo "✓ JavaScript detected: $(wc -l < js_files.txt 2>/dev/null || echo 0) files"
        [ "$HAS_RUST" = true ] && echo "✓ Rust detected: $(wc -l < rust_files.txt 2>/dev/null || echo 0) files"
        [ "$HAS_KOTLIN" = true ] && echo "✓ Kotlin detected: $(wc -l < kotlin_files.txt 2>/dev/null || echo 0) files"
        [ "$HAS_SWIFT" = true ] && echo "✓ Swift detected: $(wc -l < swift_files.txt 2>/dev/null || echo 0) files"
        [ "$HAS_JAVA" = true ] && echo "✓ Java detected: $(wc -l < java_files.txt 2>/dev/null || echo 0) files"
        [ "$HAS_FLUTTER" = true ] && echo "✓ Dart detected: $(wc -l < flutter_files.txt 2>/dev/null || echo 0) files"
        
        # Export to outputs
        echo "has_cpp=$HAS_CPP" >> $GITHUB_OUTPUT
        echo "has_js=$HAS_JS" >> $GITHUB_OUTPUT
        echo "has_rust=$HAS_RUST" >> $GITHUB_OUTPUT
        echo "has_kotlin=$HAS_KOTLIN" >> $GITHUB_OUTPUT
        echo "has_swift=$HAS_SWIFT" >> $GITHUB_OUTPUT
        echo "has_java=$HAS_JAVA" >> $GITHUB_OUTPUT
        echo "has_flutter=$HAS_FLUTTER" >> $GITHUB_OUTPUT
        
        # Save action path for later steps
        echo "ACTION_PATH=$ACTION_PATH" >> $GITHUB_ENV
    
    - name: Install C/C++ tools
      if: steps.detect.outputs.has_cpp == 'true'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y cppcheck
    
    - name: Setup Node.js
      if: steps.detect.outputs.has_js == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Rust
      if: steps.detect.outputs.has_rust == 'true'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    
    - name: Setup Java
      if: steps.detect.outputs.has_java == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Kotlin linter
      if: steps.detect.outputs.has_kotlin == 'true'
      shell: bash
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint
        chmod +x ktlint
        sudo mv ktlint /usr/local/bin/
    
    - name: Run sanity checks
      if: steps.changed-files.outputs.any_changed == 'true'
      id: run-checks
      continue-on-error: true
      shell: bash
      run: |
        echo "================================"
        echo "   RUNNING SANITY CHECKS"
        echo "================================"
        echo ""
        
        OVERALL_STATUS=0
        ACTION_PATH="${{ github.action_path }}"
        
        # Run C/C++ checks
        if [ "${{ steps.detect.outputs.has_cpp }}" = "true" ]; then
          echo ">>> Running C/C++ checks..."
          if bash "$ACTION_PATH/scripts/cpp-check.sh" 2>&1 | tee check_results.txt; then
            echo "✅ C/C++ checks passed"
          else
            echo "❌ C/C++ checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Run JavaScript checks
        if [ "${{ steps.detect.outputs.has_js }}" = "true" ]; then
          echo ">>> Running JavaScript checks..."
          if bash "$ACTION_PATH/scripts/js-check.sh" 2>&1 | tee -a check_results.txt; then
            echo "✅ JavaScript checks passed"
          else
            echo "❌ JavaScript checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Run Rust checks
        if [ "${{ steps.detect.outputs.has_rust }}" = "true" ]; then
          echo ">>> Running Rust checks..."
          if bash "$ACTION_PATH/scripts/rust-check.sh" 2>&1 | tee -a check_results.txt; then
            echo "✅ Rust checks passed"
          else
            echo "❌ Rust checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Run Kotlin checks
        if [ "${{ steps.detect.outputs.has_kotlin }}" = "true" ]; then
          echo ">>> Running Kotlin checks..."
          if bash "$ACTION_PATH/scripts/kotlin-check.sh" 2>&1 | tee -a check_results.txt; then
            echo "✅ Kotlin checks passed"
          else
            echo "❌ Kotlin checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Run Swift checks
        if [ "${{ steps.detect.outputs.has_swift }}" = "true" ]; then
          echo ">>> Running Swift checks..."
          if bash "$ACTION_PATH/scripts/swift-check.sh" 2>&1 | tee -a check_results.txt; then
            echo "✅ Swift checks passed"
          else
            echo "❌ Swift checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Run Java checks
        if [ "${{ steps.detect.outputs.has_java }}" = "true" ]; then
          echo ">>> Running Java checks..."
          if bash "$ACTION_PATH/scripts/java-check.sh" 2>&1 | tee -a check_results.txt; then
            echo "✅ Java checks passed"
          else
            echo "❌ Java checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Run Flutter checks
        if [ "${{ steps.detect.outputs.has_flutter }}" = "true" ]; then
          echo ">>> Running Flutter checks..."
          if bash "$ACTION_PATH/scripts/flutter-check.sh" 2>&1 | tee -a check_results.txt; then
            echo "✅ Flutter checks passed"
          else
            echo "❌ Flutter checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        fi
        
        # Final summary
        echo "================================"
        if [ $OVERALL_STATUS -eq 0 ]; then
          echo "✅ ALL SANITY CHECKS PASSED"
          echo "status=success" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "❌ SANITY CHECKS FAILED"
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi
    
    - name: Post results as PR comment
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const status = '${{ steps.run-checks.outputs.status }}';
          const statusEmoji = status === 'success' ? '✅' : '❌';
          const statusText = status === 'success' ? 'PASSED' : 'FAILED';
          
          // Read check results
          let results = '';
          try {
            results = fs.readFileSync('check_results.txt', 'utf8');
          } catch (error) {
            results = 'Could not read check results';
          }
          
          let errorSummary = '';
          
          if (status === 'failure') {
            const lines = results.split('\n');
            errorSummary = '\n## 🚨 Key Issues Found:\n\n';
            
            let currentLanguage = '';
            let languageErrors = {};
            
            // Parse errors by language
            for (let i = 0; i < lines.length; i++) {
              const line = lines[i];
              
              // Detect language sections
              if (line.includes('C/C++ SANITY CHECK')) {
                currentLanguage = 'C/C++';
                languageErrors[currentLanguage] = [];
              } else if (line.includes('RUST SANITY CHECK')) {
                currentLanguage = 'Rust';
                languageErrors[currentLanguage] = [];
              } else if (line.includes('JAVASCRIPT SANITY CHECK')) {
                currentLanguage = 'JavaScript';
                languageErrors[currentLanguage] = [];
              } else if (line.includes('KOTLIN SANITY CHECK')) {
                currentLanguage = 'Kotlin';
                languageErrors[currentLanguage] = [];
              } else if (line.includes('JAVA SANITY CHECK')) {
                currentLanguage = 'Java';
                languageErrors[currentLanguage] = [];
              } else if (line.includes('SWIFT SANITY CHECK')) {
                currentLanguage = 'Swift';
                languageErrors[currentLanguage] = [];
              } else if (line.includes('FLUTTER/DART SANITY CHECK')) {
                currentLanguage = 'Dart/Flutter';
                languageErrors[currentLanguage] = [];
              }
              
              // Capture error lines (format: file:line: error/warning: message)
              if (currentLanguage && line.match(/.*:\d+:.*(?:error|warning):/)) {
                languageErrors[currentLanguage].push(line.trim());
              }
            }
            
            // Build error summary
            let totalErrors = 0;
            for (const [lang, errors] of Object.entries(languageErrors)) {
              if (errors.length > 0) {
                totalErrors += errors.length;
                errorSummary += `### ${lang}\n`;
                errors.forEach(error => {
                  errorSummary += `${error}\n`;
                });
                errorSummary += '\n';
              }
            }
            
            if (totalErrors > 0) {
              errorSummary += `**Total issues found: ${totalErrors}**\n\n`;
            }
            
            errorSummary += '---\n';
          }
          
          // Get checked languages
          const languagesList = [];
          if ('${{ steps.detect.outputs.has_cpp }}' === 'true') languagesList.push('C/C++');
          if ('${{ steps.detect.outputs.has_js }}' === 'true') languagesList.push('JavaScript/TypeScript');
          if ('${{ steps.detect.outputs.has_rust }}' === 'true') languagesList.push('Rust');
          if ('${{ steps.detect.outputs.has_kotlin }}' === 'true') languagesList.push('Kotlin');
          if ('${{ steps.detect.outputs.has_swift }}' === 'true') languagesList.push('Swift');
          if ('${{ steps.detect.outputs.has_java }}' === 'true') languagesList.push('Java');
          if ('${{ steps.detect.outputs.has_flutter }}' === 'true') languagesList.push('Dart/Flutter');
          
          const body = `## ${statusEmoji} Sanity Check ${statusText}
          
          ${status === 'failure' ? '⚠️ **Action Required:** Please fix the issues below before merging.\n' : '✅ **All checks passed!** Your code meets quality standards.\n'}
          
          **Languages Checked:** ${languagesList.join(', ') || 'None'}
          
          ${errorSummary}
          
          <details>
          <summary>📋 Click to view full detailed results (with code context)</summary>
          
          \`\`\`
          ${results}
          \`\`\`
          
          </details>
          
          ---
          ${status === 'failure' ? '**Next Steps:** Fix the reported issues, commit your changes, and the checks will re-run automatically.\n\n' : ''}*Automated sanity checks completed at ${new Date().toISOString()}*`;
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
    
    - name: Add label
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const status = '${{ steps.run-checks.outputs.status }}';
          const label = status === 'success' ? 'sanity-check-passed' : 'sanity-check-failed';
          const oppositeLabel = status === 'success' ? 'sanity-check-failed' : 'sanity-check-passed';
          
          console.log(`Status: ${status}`);
          console.log(`Adding label: ${label}`);
          console.log(`Removing label: ${oppositeLabel}`);
          
          // Remove opposite label if it exists
          try {
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: oppositeLabel
            });
            console.log(`✅ Removed ${oppositeLabel}`);
          } catch (error) {
            console.log(`Label ${oppositeLabel} doesn't exist, skipping removal`);
          }
          
          // Add the current label
          try {
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            });
            console.log(`✅ Added ${label}`);
          } catch (error) {
            console.error(`Failed to add label: ${error.message}`);
            // Try to create the label first if it doesn't exist
            try {
              const color = status === 'success' ? '0e8a16' : 'd73a4a';
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label,
                color: color,
                description: `Sanity check ${status === 'success' ? 'passed' : 'failed'}`
              });
              console.log(`✅ Created label ${label}`);
              // Try adding again after creation
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [label]
              });
              console.log(`✅ Added ${label} after creation`);
            } catch (createError) {
              console.error(`Failed to create/add label: ${createError.message}`);
            }
          }
    
    - name: Fail workflow if checks failed
      if: steps.run-checks.outputs.status == 'failure'
      shell: bash
      run: |
        echo "::error::Sanity checks failed. Please fix the issues before merging."
        exit 1