name: 'Multi-Language Sanity Check'
description: 'Automated sanity checks and vulnerability scanning for multi-language projects'
author: 'Surabhis12'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for posting comments and managing labels'
    required: true

outputs:
  status:
    description: 'Overall status of sanity checks (success/failure)'
    value: ${{ steps.run-checks.outputs.status }}

runs:
  using: 'composite'
  steps:
    # ------------------------------------------------------------
    # Detect changed files
    # ------------------------------------------------------------
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@b3f7d4d8f7cbdac2f70fdd7fa34e2ad5cdbec2b4
      with:
        files: |
          **/*.c
          **/*.cpp
          **/*.h
          **/*.hpp
          **/*.js
          **/*.jsx
          **/*.ts
          **/*.tsx
          **/*.rs
          **/*.kt
          **/*.swift
          **/*.java
          **/*.dart

    # ------------------------------------------------------------
    # Language detection (RESTORED – critical)
    # ------------------------------------------------------------
    - name: Detect languages
      id: detect
      shell: bash
      run: |
        set -euo pipefail

        echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt

        HAS_CPP=false
        HAS_JS=false
        HAS_RUST=false
        HAS_KOTLIN=false
        HAS_SWIFT=false
        HAS_JAVA=false
        HAS_FLUTTER=false

        while IFS= read -r file; do
          case "$file" in
            *.c|*.cpp|*.h|*.hpp) HAS_CPP=true ;;
            *.js|*.jsx|*.ts|*.tsx) HAS_JS=true ;;
            *.rs) HAS_RUST=true ;;
            *.kt) HAS_KOTLIN=true ;;
            *.swift) HAS_SWIFT=true ;;
            *.java) HAS_JAVA=true ;;
            *.dart) HAS_FLUTTER=true ;;
          esac
        done < changed_files.txt

        echo "has_cpp=$HAS_CPP" >> "$GITHUB_OUTPUT"
        echo "has_js=$HAS_JS" >> "$GITHUB_OUTPUT"
        echo "has_rust=$HAS_RUST" >> "$GITHUB_OUTPUT"
        echo "has_kotlin=$HAS_KOTLIN" >> "$GITHUB_OUTPUT"
        echo "has_swift=$HAS_SWIFT" >> "$GITHUB_OUTPUT"
        echo "has_java=$HAS_JAVA" >> "$GITHUB_OUTPUT"
        echo "has_flutter=$HAS_FLUTTER" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------
    # Tool setup (PINNED + SAFE)
    # ------------------------------------------------------------
    - name: Setup Node.js
      if: steps.detect.outputs.has_js == 'true'
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: '20'

    - name: Setup Rust
      if: steps.detect.outputs.has_rust == 'true'
      uses: dtolnay/rust-toolchain@f3b6fddbdc8f7dfbbfc46c8a7f5a7d2c7b68b61f
      with:
        toolchain: stable
        components: clippy

    - name: Setup Java
      if: steps.detect.outputs.has_java == 'true'
      uses: actions/setup-java@4e7e684fbb6e33f88ecb2cf1e6b3797739cf499b
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Kotlin linter
      if: steps.detect.outputs.has_kotlin == 'true'
      shell: bash
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.0.1/ktlint
        chmod +x ktlint
        sudo mv ktlint /usr/local/bin/

    # ------------------------------------------------------------
    # Run sanity checks (SAFE timeout, original behavior)
    # ------------------------------------------------------------
    - name: Run sanity checks
      id: run-checks
      shell: bash
      run: |
        echo "================================"
        echo "   RUNNING SANITY CHECKS"
        echo "================================"
        echo ""

        OVERALL_STATUS=0
        ACTION_PATH="${{ github.action_path }}"
        TIMEOUT=600

        run_check () {
          local name="$1"
          local script="$2"

          echo ">>> Running $name checks..."
          if timeout "${TIMEOUT}s" bash "$script" 2>&1 | tee "${name}_check.txt"; then
            echo "✅ $name checks passed"
          else
            echo "❌ $name checks failed"
            OVERALL_STATUS=1
          fi
          echo ""
        }

        [[ "${{ steps.detect.outputs.has_cpp }}" == "true" ]] && run_check cpp "$ACTION_PATH/scripts/cpp-check.sh"
        [[ "${{ steps.detect.outputs.has_js }}" == "true" ]] && run_check js "$ACTION_PATH/scripts/js-check.sh"
        [[ "${{ steps.detect.outputs.has_rust }}" == "true" ]] && run_check rust "$ACTION_PATH/scripts/rust-check.sh"
        [[ "${{ steps.detect.outputs.has_kotlin }}" == "true" ]] && run_check kotlin "$ACTION_PATH/scripts/kotlin-check.sh"
        [[ "${{ steps.detect.outputs.has_swift }}" == "true" ]] && run_check swift "$ACTION_PATH/scripts/swift-check.sh"
        [[ "${{ steps.detect.outputs.has_java }}" == "true" ]] && run_check java "$ACTION_PATH/scripts/java-check.sh"
        [[ "${{ steps.detect.outputs.has_flutter }}" == "true" ]] && run_check flutter "$ACTION_PATH/scripts/flutter-check.sh"

        cat *_check.txt 2>/dev/null > check_results.txt || echo "No check results" > check_results.txt

        if [ $OVERALL_STATUS -eq 0 ]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
          exit 0
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
          exit 1
        fi

    # ------------------------------------------------------------
    # PR COMMENT (UNCHANGED – EXACT UX)
    # ------------------------------------------------------------
    - name: Post results as PR comment
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@7d4b21e37b0c9d7f7b7b60db9a1c0d2b0c3e92b3
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const status = '${{ steps.run-checks.outputs.status }}';
          const statusEmoji = status === 'success' ? '✅' : '❌';
          const statusText = status === 'success' ? 'PASSED' : 'FAILED';

          let results = '';
          try { results = fs.readFileSync('check_results.txt', 'utf8'); }
          catch { results = 'Could not read check results'; }

          let errorSummary = '';
          if (status === 'failure') {
            errorSummary = '\n## 🚨 Key Issues Found:\n\n' + results + '\n---\n';
          }

          const languagesList = [];
          if ('${{ steps.detect.outputs.has_cpp }}' === 'true') languagesList.push('C/C++');
          if ('${{ steps.detect.outputs.has_js }}' === 'true') languagesList.push('JavaScript/TypeScript');
          if ('${{ steps.detect.outputs.has_rust }}' === 'true') languagesList.push('Rust');
          if ('${{ steps.detect.outputs.has_kotlin }}' === 'true') languagesList.push('Kotlin');
          if ('${{ steps.detect.outputs.has_swift }}' === 'true') languagesList.push('Swift');
          if ('${{ steps.detect.outputs.has_java }}' === 'true') languagesList.push('Java');
          if ('${{ steps.detect.outputs.has_flutter }}' === 'true') languagesList.push('Dart/Flutter');

          const body = `## ${statusEmoji} Sanity Check ${statusText}

          ${status === 'failure'
            ? '⚠️ **Action Required:** Please fix the issues below before merging.\n'
            : '✅ **All checks passed!** Your code meets quality standards.\n'}

          **Languages Checked:** ${languagesList.join(', ') || 'None'}

          ${errorSummary}

          <details>
          <summary>📋 Click to view full detailed results</summary>

          \`\`\`
          ${results}
          \`\`\`

          </details>

          ---
          ${status === 'failure'
            ? '**Next Steps:** Fix the reported issues, commit your changes, and the checks will re-run automatically.\n\n'
            : ''}*Automated sanity checks completed at ${new Date().toISOString()}*`;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });

    # ------------------------------------------------------------
    # Labels (UNCHANGED – EXACT BEHAVIOR)
    # ------------------------------------------------------------
    - name: Add label
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@7d4b21e37b0c9d7f7b7b60db9a1c0d2b0c3e92b3
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const status = '${{ steps.run-checks.outputs.status }}';
          const label = status === 'success' ? 'sanity-check-passed' : 'sanity-check-failed';
          const oppositeLabel = status === 'success' ? 'sanity-check-failed' : 'sanity-check-passed';

          try {
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: oppositeLabel
            });
          } catch {}

          try {
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            });
          } catch {
            const color = status === 'success' ? '0e8a16' : 'd73a4a';
            await github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label,
              color
            });
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label]
            });
          }
